### ISSUE TITLE
Support Int or Other Doctrine Types

### ISSUE THREAD

**Issue by Tigerman55** [acelaya/doctrine-enum-type#22]
Do you think it would be useful to have the ability to have an optional parameter when you register the enum type specifying the doctrine field type and change the doctrine type corresponding to that so that it is not always varchar 255? I have enum values that would work perfect with just being tinyint or int in the database.

**Comment by acelaya** [comment]
It is already possible to override that: https://github.com/acelaya/doctrine-enum-type#customize-sql-declaration

The `varchar(255)` declaration is just for convenience.
