### ISSUE TITLE
Schema Tool Update not Caching

### ISSUE THREAD

**Issue by Tigerman55** [acelaya/doctrine-enum-type#23]
I'm having an issue where when I run `orm:schema-tool:update --dump-sql` from the console, it always displays the doctrine enum type queries associated with my entities, even though I have already executed them to update the database schema. I'm not sure why my enum types are not being cached in the doctrine schema.

**Comment by Tigerman55** [comment]
I determined that this is required to "cache" a custom type `$entityManager->getConnection()->getDatabasePlatform()->registerDoctrineTypeMapping('php_enum_type', 'php_enum_type');`

Per Doctrine 2 docs: "To convert the underlying database type of your new "mytype" directly into an instance of MyType when performing schema operations, the type has to be registered with the database platform as well"

**Comment by acelaya** [comment]
That's good to know. I'll probably document that. Thanks :)
