### ISSUE TITLE
Needs instructionsof how to make it work with symfony

### ISSUE THREAD

**Issue by Arkemlar** [acelaya/doctrine-enum-type#38]

**Comment by acelaya** [comment]
Hello @Arkemlar 
Sorry I couldn't get to this earlier. I was planning to investigate this after work (so in about 4 hours).
Did you manage to fix it?

**Comment by Arkemlar** [comment]
Hello @acelaya, well I feel like I understood what was wrong, but not tested it because decided to combine some different approaches of doctrine enums implementation into custom one. By the way it would be very good to have integration example for others because I struggled around half day to investigate doctrine internals to understand why it doesnt work. And when I understood - I had enough knoladge to implement my own solution.
