### ISSUE TITLE
Idea for automatic type definition

### ISSUE THREAD

**Issue by Nemo64** [acelaya/doctrine-enum-type#4]
Currenty every doctrine type has to be defined by hand but I think that could be reduced. There just needs to be one Type definition for Enum. Doctrines type registry does not allow a lot of magic but it might be enough to configure the type. Here is what I think:

```
public static function addEnumType ($enumClass) {
    $classShortName = substr(strrchr(get_class($this), '\\'), 1);
    // the class short name may need to be underscorized
    Type::addType($classShortName, 'Enum\\Type\\Somewhere');
    Type::getType($classShortName)->setClass($enumClass);
}
```

The trick is that `Type::getType` returns an instance of the type. Also the abstract `getName` method is not used by the type registry so it could just lie on the initial `addType` call.

**Comment by acelaya** [comment]
The fact that you have to define every enum type is one of the things I would like to improve, so if you have an idea, I'm willing to listen to it.
However I'm not sure if I follow you. Could you elaborate? :-)

**Comment by Nemo64** [comment]
Ok, so, why do we need to define a new field type for every Enum? Because Doctrine wants just a class for every field type and normally not allowing to pass other data. But how about creating a doctrine type like this:

``` PHP
class EnumType extends Type {
    private $enumClass;
    private $typeName;

    // i use this method later...
    private function define ($typeName, $enumClass) {
        $this->typeName = $typeName;
        $this->enumClass = $enumClass;
    }

    // this method is not used by the Type class
    // therefor it is not required to immediately return the correct type name
    public function getName () {
        return $this->typeName ?: 'enum';
    }

    public static function addEnum ($typeName, $enumClass) {
        // type does not check if we already added the class, just if the type name is unique
        // therefor it is no problem reusing the same class for 30 different types
        // the only problem is that it is impossible to define how doctrine creates an instance
        Type::addType($typeName, __CLASS__);

        // so here the trick
        // the get method creates the type instance and now it is possible to pass information
        Type::getType($typeName)->define($typeName, $enumClass);
        // the same type instance will now be reused if dbal accesses it.
        // so now we have created a doctrine field type with the name in $typeName
    }

    public function convertToPHPValue($value, AbstractPlatform $platform) {
        // so now it is possible to use the type definition here.
        return new $this->enumClass($value);
    }

    // ...
}
```

So if a type like the one above exist you could simply add an enum to doctrine like this:

``` PHP
EnumType::addEnum('gender', GenderEnum::class);
```

**Comment by acelaya** [comment]
I don't see any advantage in your approach.
You still need to create a different enum class for each type, and while registering them, instead of doing something like this:

``` php
Type::addType('php_enum_action', ActionEnumType::class);
Type::addType('php_enum_another', AnotherEnumType::class);
Type::addType('php_enum_foo', FooEnumType::class);
```

You have to do this

``` php
EnumType::addEnum('php_enum_action', ActionEnumType::class);
EnumType::addEnum('php_enum_another', AnotherEnumType::class);
EnumType::addEnum('php_enum_foo', FooEnumType::class);
```

The only advantage I see is that you don't need to define the abstract stuff from `AbstractPhpEnumType`, but I don't think it's worth the change.

Also, your approach forces all types to be instantiated on every request, while they are usually lazy loaded when needed. That could be a performance problem on big projects.

However, you can still use your approach with this library, I think it is perfectly compatible :-)
You could do that with any doctrine type indeed.

**Comment by Nemo64** [comment]
No, exactly that falls away. You pass the enum to the new add type method.
The general enum type is then used for all enums with different names. So
with my approach you don't have to write a doctrine type, you just need to
register your enum.

Alejandro Celaya notifications@github.com schrieb am Fr., 29. Apr. 2016,
22:53:

**Comment by acelaya** [comment]
Right, I did not get it. I see it now.
However, I still don't like the fact that all types are instantiated from the beginning. I would like to see some performance benchmarks before implementing this.

**Comment by Nemo64** [comment]
That's why this is an idea and not an implementation. But what scales are
we talking about? Even with 30 enums there are 30 instances then. I would
even argue that loading 30 different classes would be slower and consume
more ram than creating 30 instances of the same class.

Alejandro Celaya notifications@github.com schrieb am Fr., 29. Apr. 2016,
23:21:

**Comment by acelaya** [comment]
The type classes won't be loaded until they are instantiated. The `use` statements and `Foo::class` ussages do not hit the autoloader.

**Comment by acelaya** [comment]
I completely forgot about this thread.
I have been thinking about this later, and I think there isn't a better solution. It might be a little slower, but I don't think any project ends with more than a couple of enums, and in that case the performance impact isn't so big compared with the reduction on time and verbosity.

I'm going to implement this approach for v2.

Thank you!

**Comment by acelaya** [comment]
By the way, do you have a twitter account or some way to mention you?
I'll tweet about the new release and probably blog about it, and I wan't you to be mentioned for finding this approach.

**Comment by Nemo64** [comment]
@acelaya I'm [TheTrueNemo](https://twitter.com/TheTrueNemo) on twitter. Nice that you have revisited this issue almost a year after I created it. ;)

**Comment by acelaya** [comment]
Yep... Sorry for the delay 😅


--
Alejandro Celaya Alastrué
