### ISSUE TITLE
Why name is private?

### ISSUE THREAD

**Issue by 6rGVH32F823ProYH** [acelaya/doctrine-enum-type#63]
https://github.com/acelaya/doctrine-enum-type/blob/1a37ad15c35258890ecd2a18992bcd88b64937cb/src/Type/PhpEnumType.php#L21

**Comment by acelaya** [comment]
Why not?

**Comment by 6rGVH32F823ProYH** [comment]
'Cause cannot extend from PhpEnumType without overriding getName method and register in symfony yml cfg
![image](https://user-images.githubusercontent.com/5332264/111044174-fc02df80-8457-11eb-8f68-2534b950a615.png)

**Comment by acelaya** [comment]
I still don't follow. Why do you need to create your own class extending `PhpEnumType`? Can you elaborate?
